# Generated by Django 4.1.4 on 2023-01-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_favorites_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'verbose_name': 'Рецепт-ингредиент', 'verbose_name_plural': 'Рецепты-ингредиенты'},
        ),
    ]
