# Generated by Django 4.1.4 on 2023-01-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_recipe_get_favorite_count_alter_amount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='get_favorite_count',
        ),
    ]
