# Generated by Django 4.1.4 on 2023-01-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_recipe_get_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='get_favorite_count',
        ),
    ]
