# Generated by Django 4.1.4 on 2023-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_recipe_get_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавления в избранное'),
        ),
    ]
