# Generated by Django 4.1.4 on 2023-01-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_recipe_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_count',
        ),
    ]
